@startuml
MenuGlowne --> BankowoscInternetowa
BankowoscInternetowa --> Bankomat
Bankomat --> PanelAdmina

MenuGlowne --> ScenariuszBI
MenuGlowne --> ScenariuszBankomat
MenuGlowne --> ScenariuszAdmin

SystemBankowy +-- Konto
SystemBankowy +-- Transakcja
@enduml